tg_config:
    bot_token: ""
    chat_id: -100100000000
    dev_chat_id: 30000000
tw_config:
    bearer_token: ""
    handles:
        - AcalaNetwork
        - KaruraNetwork
        - ShidenNetwork
        - AstarNetwork
        - bifrost_finance
        - GenshiroDeFi
        - CrustNetwork
        - NodleNetwork
        - CalamariNetwork
        - ParallelFi
        - MoonriverNW
        - MoonbeamNetwork
        - centrifuge
        - altair_network
        - integri_t_e_e
        - SubsocialChain
        - PhalaNetwork
        - hydra_dx
        - kintsugi_btc
        - interlayHQ
        - bsx_finance
        - Kiltprotocol
        - RobonomicsESP
        - sora_xor
        - Unique_NFTchain
        - encointer
        - ComposableFin
        - Picasso_Network
        - enjin
        - MangataFinance
        - clover_finance
        - DoraFactory
        - litentry
        - polkadex
        - Coinversation_
        - Listen_io
        - HeyKabocha
        - _ParaState
        - bitdotcountry
        - subdao_network
        - KonomiNetwork
        - Kylin_Network
        - standardweb3
        - ZeitgeistPM
        - crustnetwork
        - mantanetwork
        - PontemNetwork
        - apronofficial1
        - IdavollN
        - oak_network
        - DarwiniaNetwork
        - AresProtocolLab
        - laminarprotocol
        - InvArchNetwork
        - ImbueNetwork
        - SubgameBase
        - SubGame_Network
        - shadows_defi
        - polkafoundry
        - NetworkSubspace
        - TrustBase_Net
        - loomnetwork
        - Mathwallet
        - zCloakNetwork
        - chainx_org
        - origin_trail
        - JoystreamApp
        - ternoa_
        - DataHighway_DHX
        - UniartsNetwork
        - Totem_live_
        - zerodotio
        - patractlabs
        - CelerNetwork
        - cerenetwork
        - docknetwork
        - DefiStone
        - AjunaNetwork
        - Stafi_Protocol
        - Nsure_network
        - akropolisio
        - deeper_network
        - RubyProtocol
        - t3rn_io
        - OpensquareN
        - DatDotOrg
        - evercityeco
        - ZeroPoolNetwork
        - Dipole_Tech
        - caelumlabs
        - definexpoland
        - snowfork_inc
        - teaprojectorg
        - subquerynetwork
        - bluzellehq
        - riodefiofficial
        - ReefDeFi
        - tidaldefi
        - LinearFinance
        - mxcfoundation
        - covercompared
        - ParalinkNetwork
        - gear_techs
        - ethalend
        - fractalprtcl
        - Royale_Finance
        - AutomataNetwork
        - Exeedme
        - MANTRADAO
        - EdgewareDAO
        - BondlyFinance
        - RaiFinance
        - hellobandot
        - energywebx
        - realpolkabridge
        - OAX_Foundation
        - XPredictMarket
        - compoundfinance
        - kulupunetwork
        - peaqnetwork
        - SEOR001
        - acuity_social
        - MarcoPoloGlobal
        - curio_invest
        - SunriseProtocol
        - Bestay_bsy
        - wivteam
        - bitgreen_
        - dego_finance
        - gamedaoco
        - ShiftNrg
        - PulseNetwork_
        - everlife_ai
        - oct_network 